from typing import Any, ClassVar

from typing import overload
import pyarrow.lib

class Buffer(pyarrow.lib._Weakrefable):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    address: Any
    is_cpu: Any
    is_mutable: Any
    parent: Any
    size: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def equals(self, Bufferother) -> Any: ...
    def hex(self) -> Any: ...
    def slice(self, offset = ..., length = ...) -> Any: ...
    def to_pybytes(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce_ex__(self, protocol) -> Any: ...

def _parse_json_plan(plan) -> Any: ...
def frombytes(*args, **kwargs) -> Any: ...
def get_supported_functions() -> Any: ...
def py_buffer(obj) -> Any: ...
@overload
def run_query(plan, table_provider = ...) -> Any: ...
@overload
def run_query(buf, table_provider) -> Any: ...
def tobytes(o) -> Any: ...
