from typing import Any, ClassVar

from typing import overload
import _abc
import _io
import collections.abc
import enum
import importlib._bootstrap
import io
DEFAULT_BUFFER_SIZE: int
NA: NullScalar
Type_BINARY: int
Type_BOOL: int
Type_DATE32: int
Type_DATE64: int
Type_DECIMAL128: int
Type_DECIMAL256: int
Type_DENSE_UNION: int
Type_DICTIONARY: int
Type_DOUBLE: int
Type_DURATION: int
Type_FIXED_SIZE_BINARY: int
Type_FIXED_SIZE_LIST: int
Type_FLOAT: int
Type_HALF_FLOAT: int
Type_INT16: int
Type_INT32: int
Type_INT64: int
Type_INT8: int
Type_INTERVAL_MONTH_DAY_NANO: int
Type_LARGE_BINARY: int
Type_LARGE_LIST: int
Type_LARGE_STRING: int
Type_LIST: int
Type_MAP: int
Type_NA: int
Type_SPARSE_UNION: int
Type_STRING: int
Type_STRUCT: int
Type_TIME32: int
Type_TIME64: int
Type_TIMESTAMP: int
Type_UINT16: int
Type_UINT32: int
Type_UINT64: int
Type_UINT8: int
UnionMode_DENSE: int
UnionMode_SPARSE: int
V1: importlib._bootstrap.MetadataVersion
V2: importlib._bootstrap.MetadataVersion
V3: importlib._bootstrap.MetadataVersion
V4: importlib._bootstrap.MetadataVersion
V5: importlib._bootstrap.MetadataVersion
_NULL: NullScalar
__pc: None
_break_traceback_cycle_from_frame: function
_default_context_initialized: bool
_default_serialization_context: SerializationContext
_is_path_like: function
_pandas_api: _PandasAPIShim
_python_extension_types_registry: list
_registry_nanny: _ExtensionRegistryNanny
_stringify_path: function
contextmanager: function
cpp_build_info: importlib._bootstrap.BuildInfo
cpp_version: str
cpp_version_info: importlib._bootstrap.VersionInfo
have_signal_refcycle: bool
namedtuple: function

class Array(_PandasConvertible):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    _name: Any
    nbytes: Any
    null_count: Any
    offset: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _debug_print(self) -> Any: ...
    def _export_to_c(self, out_ptr, out_schema_ptr = ...) -> Any: ...
    def _import_from_c(self, in_ptr, type) -> Any: ...
    def _to_pandas(self, options, types_mapper = ..., **kwargs) -> Any: ...
    def buffers(self) -> Any: ...
    def cast(self, target_type = ..., safe = ..., options = ...) -> Any: ...
    def dictionary_encode(self, null_encoding = ...) -> Any: ...
    @overload
    def diff(self, Arrayother) -> Any: ...
    @overload
    def diff(self, right) -> Any: ...
    def drop_null(self) -> Any: ...
    def equals(self, Arrayother) -> Any: ...
    def fill_null(self, fill_value) -> Any: ...
    def filter(self, *args, **kwargs) -> Any: ...
    def format(self, **kwargs) -> Any: ...
    def from_buffers(self, DataTypetype, length, buffers, null_count = ..., offset = ..., children = ...) -> Any: ...
    def from_pandas(self, obj, mask = ..., type = ..., boolsafe = ..., MemoryPoolmemory_pool = ...) -> Any: ...
    def get_total_buffer_size(self) -> Any: ...
    def index(self, *args, **kwargs) -> Any: ...
    def is_null(self, *args, **kwargs) -> Any: ...
    def is_valid(self) -> Any: ...
    def slice(self, offset = ..., length = ...) -> Any: ...
    def sum(self, **kwargs) -> Any: ...
    def take(self, indices) -> Any: ...
    def to_numpy(self, zero_copy_only = ..., writable = ...) -> Any: ...
    def to_pylist(self) -> Any: ...
    def to_string(self, *args, **kwargs) -> Any: ...
    def tolist(self) -> Any: ...
    def unique(self) -> Any: ...
    def validate(self, *args, **kwargs) -> Any: ...
    def value_counts(self) -> Any: ...
    def view(self, target_type) -> Any: ...
    def __array__(self, dtype = ...) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __iter__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __sizeof__(self) -> Any: ...

class ArrowCancelled(ArrowException):
    def __init__(self, message, signum = ...) -> Any: ...

class ArrowCapacityError(ArrowException): ...

class ArrowException(Exception): ...

class ArrowIOError(Exception):
    characters_written: Any
    errno: Any
    filename: Any
    filename2: Any
    strerror: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class ArrowIndexError(IndexError, ArrowException): ...

class ArrowInvalid(ValueError, ArrowException): ...

class ArrowKeyError(KeyError, ArrowException): ...

class ArrowMemoryError(MemoryError, ArrowException): ...

class ArrowNotImplementedError(NotImplementedError, ArrowException): ...

class ArrowSerializationError(ArrowException): ...

class ArrowTypeError(TypeError, ArrowException): ...

class BaseExtensionType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    extension_name: Any
    storage_type: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def wrap_array(self, storage) -> Any: ...

class BaseListArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def flatten(self) -> Any: ...
    @overload
    def value_lengths(self) -> Any: ...
    @overload
    def value_lengths(self) -> Any: ...
    @overload
    def value_parent_indices(self) -> Any: ...
    @overload
    def value_parent_indices(self) -> Any: ...

class BinaryArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    total_values_length: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class BinaryScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_buffer(self) -> Any: ...
    def as_py(self) -> Any: ...

class BooleanArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    false_count: Any
    true_count: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class BooleanScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Buffer(_Weakrefable):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    address: Any
    is_cpu: Any
    is_mutable: Any
    parent: Any
    size: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def equals(self, Bufferother) -> Any: ...
    def hex(self) -> Any: ...
    def slice(self, offset = ..., length = ...) -> Any: ...
    def to_pybytes(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce_ex__(self, protocol) -> Any: ...

class BufferOutputStream(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def getvalue(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class BufferReader(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class BufferedIOBase(_io._BufferedIOBase, io.IOBase):
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __abstractmethods__: ClassVar[frozenset] = ...

class BufferedInputStream(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def detach(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class BufferedOutputStream(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def detach(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class BuildInfo(tuple):
    _asdict: ClassVar[function] = ...
    _field_defaults: ClassVar[dict] = ...
    _fields: ClassVar[tuple] = ...
    _replace: ClassVar[function] = ...
    __getnewargs__: ClassVar[function] = ...
    __match_args__: ClassVar[tuple] = ...
    __slots__: ClassVar[tuple] = ...
    build_type: Any
    compiler_flags: Any
    compiler_id: Any
    compiler_version: Any
    full_so_version: Any
    git_description: Any
    git_id: Any
    package_kind: Any
    so_version: Any
    version: Any
    version_info: Any
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def _make(cls, *args, **kwargs) -> Any: ...

class ChunkedArray(_PandasConvertible):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    _name: Any
    chunks: Any
    data: Any
    nbytes: Any
    null_count: Any
    num_chunks: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _to_pandas(self, options, types_mapper = ..., **kwargs) -> Any: ...
    def cast(self, target_type = ..., safe = ..., options = ...) -> Any: ...
    def chunk(self, i) -> Any: ...
    @overload
    def combine_chunks(self, MemoryPoolmemory_pool = ...) -> Any: ...
    @overload
    def combine_chunks(self) -> Any: ...
    @overload
    def dictionary_encode(self, null_encoding = ...) -> Any: ...
    @overload
    def dictionary_encode(self) -> Any: ...
    @overload
    def drop_null(self) -> Any: ...
    @overload
    def drop_null(self) -> Any: ...
    @overload
    def equals(self, ChunkedArrayother) -> Any: ...
    @overload
    def equals(self, n_legs) -> Any: ...
    @overload
    def equals(self, animals) -> Any: ...
    @overload
    def fill_null(self, fill_value) -> Any: ...
    @overload
    def fill_null(self, fill_value) -> Any: ...
    @overload
    def filter(self, mask, null_selection_behavior = ...) -> Any: ...
    @overload
    def filter(self, mask) -> Any: ...
    @overload
    def filter(self, mask, null_selection_behavior = ...) -> Any: ...
    @overload
    def flatten(self, MemoryPoolmemory_pool = ...) -> Any: ...
    @overload
    def flatten(self) -> Any: ...
    def format(self, **kwargs) -> Any: ...
    @overload
    def get_total_buffer_size(self) -> Any: ...
    @overload
    def get_total_buffer_size(self) -> Any: ...
    def index(self, *args, **kwargs) -> Any: ...
    def is_null(self) -> Any: ...
    @overload
    def is_valid(self) -> Any: ...
    @overload
    def is_valid(self) -> Any: ...
    @overload
    def iterchunks(self) -> Any: ...
    @overload
    def iterchunks(self) -> Any: ...
    @overload
    def length(self) -> Any: ...
    @overload
    def length(self) -> Any: ...
    def slice(self, offset = ..., length = ...) -> Any: ...
    def take(self, indices) -> Any: ...
    @overload
    def to_numpy(self) -> Any: ...
    @overload
    def to_numpy(self) -> Any: ...
    @overload
    def to_pylist(self) -> Any: ...
    @overload
    def to_pylist(self) -> Any: ...
    def to_string(self, skip_new_lines = ...) -> Any: ...
    @overload
    def unify_dictionaries(self, MemoryPoolmemory_pool = ...) -> Any: ...
    @overload
    def unify_dictionaries(self) -> Any: ...
    @overload
    def unique(self) -> Any: ...
    @overload
    def unique(self) -> Any: ...
    def validate(self, *args, **kwargs) -> Any: ...
    @overload
    def value_counts(self) -> Any: ...
    @overload
    def value_counts(self) -> Any: ...
    def __array__(self, dtype = ...) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __iter__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __sizeof__(self) -> Any: ...

class Codec(_Weakrefable):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    compression_level: Any
    name: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def compress(self, buf, asbytes = ..., memory_pool = ...) -> Any: ...
    def decompress(self, buf, decompressed_size = ..., asbytes = ..., memory_pool = ...) -> Any: ...
    def default_compression_level(self, unicodecompression) -> Any: ...
    def detect(self, path) -> Any: ...
    def is_available(self, unicodecompression) -> Any: ...
    def maximum_compression_level(self, unicodecompression) -> Any: ...
    def minimum_compression_level(self, unicodecompression) -> Any: ...
    def supports_compression_level(self, unicodecompression) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class CompressedInputStream(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class CompressedOutputStream(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class DataType(_Weakrefable):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    bit_width: Any
    id: Any
    num_buffers: Any
    num_fields: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _export_to_c(self, out_ptr) -> Any: ...
    def _import_from_c(self, in_ptr) -> Any: ...
    def equals(self, other) -> Any: ...
    def field(self, i) -> Field: ...
    def to_pandas_dtype(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __hash__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...

class Date32Array(NumericArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Date32Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Date64Array(NumericArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Date64Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Decimal128Array(FixedSizeBinaryArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Decimal128Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Decimal128Type(FixedSizeBinaryType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    precision: Any
    scale: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class Decimal256Array(FixedSizeBinaryArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Decimal256Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Decimal256Type(FixedSizeBinaryType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    precision: Any
    scale: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class DenseUnionType(UnionType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class DeserializationCallbackError(ArrowSerializationError):
    def __init__(self, message, type_id) -> Any: ...

class DictionaryArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    dictionary: Any
    indices: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def dictionary_decode(self) -> Any: ...
    def dictionary_encode(self) -> Any: ...
    def from_arrays(self, indices, dictionary, mask = ..., boolordered = ..., boolfrom_pandas = ..., boolsafe = ..., MemoryPoolmemory_pool = ...) -> Any: ...
    def from_buffers(self, DataTypetype, int64_tlength, buffers, Arraydictionary, int64_tnull_count = ..., int64_toffset = ...) -> Any: ...

class DictionaryMemo(_Weakrefable):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class DictionaryScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    dictionary: Any
    index: Any
    value: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def _reconstruct(cls, typecls, type, is_valid, index, dictionary) -> Any: ...
    def as_py(self) -> Any: ...
    def __reduce__(self) -> Any: ...

class DictionaryType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    index_type: Any
    ordered: Any
    value_type: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class DoubleArray(FloatingPointArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class DoubleScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class DurationArray(NumericArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class DurationScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    value: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class DurationType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    unit: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ExtensionArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    storage: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _to_pandas(self, options, **kwargs) -> Any: ...
    def from_storage(self, BaseExtensionTypetyp, Arraystorage) -> Any: ...
    def to_numpy(self, **kwargs) -> Any: ...

class ExtensionScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    value: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...
    def from_storage(self, BaseExtensionTypetyp, value) -> Any: ...

class ExtensionType(BaseExtensionType):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __arrow_ext_class__(self) -> Any: ...
    @classmethod
    def __arrow_ext_deserialize__(cls, typeself, storage_type, serialized) -> Any: ...
    def __arrow_ext_scalar_class__(self) -> Any: ...
    def __arrow_ext_serialize__(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...

class Field(_Weakrefable):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    metadata: Any
    name: Any
    nullable: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _export_to_c(self, out_ptr) -> Any: ...
    def _import_from_c(self, in_ptr) -> Any: ...
    def equals(self, Fieldother, boolcheck_metadata = ...) -> Any: ...
    def flatten(self) -> Any: ...
    def remove_metadata(self) -> Any: ...
    def with_metadata(self, metadata) -> Any: ...
    def with_name(self, name) -> Any: ...
    def with_nullable(self, nullable) -> Any: ...
    def with_type(self, DataTypenew_type) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __hash__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...

class FixedSizeBinaryArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class FixedSizeBinaryScalar(BinaryScalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class FixedSizeBinaryType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    byte_width: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class FixedSizeBufferWriter(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def set_memcopy_blocksize(self, int64_tblocksize) -> Any: ...
    def set_memcopy_threads(self, intnum_threads) -> Any: ...
    def set_memcopy_threshold(self, int64_tthreshold) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class FixedSizeListArray(BaseListArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    values: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @overload
    def from_arrays(self, values, list_size = ..., DataTypetype = ...) -> Any: ...
    @overload
    def from_arrays(self, values, type = ...) -> Any: ...

class FixedSizeListScalar(ListScalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class FixedSizeListType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    list_size: Any
    value_field: Any
    value_type: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class FloatArray(FloatingPointArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class FloatScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class FloatingPointArray(NumericArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class HalfFloatArray(FloatingPointArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class HalfFloatScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class IOBase(_io._IOBase):
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __abstractmethods__: ClassVar[frozenset] = ...

class Int16Array(IntegerArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Int16Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Int32Array(IntegerArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Int32Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Int64Array(IntegerArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Int64Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Int8Array(IntegerArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Int8Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class IntegerArray(NumericArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class IpcReadOptions(_Weakrefable):
    __slots__: ClassVar[tuple] = ...
    ensure_native_endian: Any
    included_fields: Any
    use_threads: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IpcWriteOptions(_Weakrefable):
    __slots__: ClassVar[tuple] = ...
    allow_64bit: Any
    compression: Any
    emit_dictionary_deltas: Any
    metadata_version: Any
    unify_dictionaries: Any
    use_legacy_format: Any
    use_threads: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class KeyValueMetadata(_Metadata, collections.abc.Mapping):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def equals(self, KeyValueMetadataother) -> Any: ...
    def get_all(self, key) -> Any: ...
    def items(self) -> Any: ...
    def key(self, i) -> Any: ...
    def keys(self) -> Any: ...
    def to_dict(self) -> Any: ...
    def value(self, i) -> Any: ...
    def values(self) -> Any: ...
    def __contains__(self, other) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __iter__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...

class LargeBinaryArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    total_values_length: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class LargeBinaryScalar(BinaryScalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class LargeListArray(BaseListArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    offsets: Any
    values: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def from_arrays(self, offsets, values, DataTypetype = ..., MemoryPoolpool = ..., mask = ...) -> Any: ...

class LargeListScalar(ListScalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class LargeListType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    value_field: Any
    value_type: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class LargeStringArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def from_buffers(self, intlength, Buffervalue_offsets, Bufferdata, Buffernull_bitmap = ..., intnull_count = ..., intoffset = ...) -> Any: ...

class LargeStringScalar(StringScalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ListArray(BaseListArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    offsets: Any
    values: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @overload
    def from_arrays(self, offsets, values, DataTypetype = ..., MemoryPoolpool = ..., mask = ...) -> Any: ...
    @overload
    def from_arrays(self, offsets, values) -> Any: ...
    @overload
    def from_arrays(self, offsets, values) -> Any: ...

class ListScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    values: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> Any: ...

class ListType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    value_field: Any
    value_type: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class LoggingMemoryPool(MemoryPool):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class MapArray(ListArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    items: Any
    keys: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def from_arrays(self, offsets, keys, items, MemoryPoolpool = ...) -> Any: ...

class MapScalar(ListScalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __iter__(self) -> Any: ...

class MapType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    item_field: Any
    item_type: Any
    key_field: Any
    key_type: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class Mapping(collections.abc.Collection):
    _abc_impl: ClassVar[_abc._abc_data] = ...
    get: ClassVar[function] = ...
    items: ClassVar[function] = ...
    keys: ClassVar[function] = ...
    values: ClassVar[function] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    __contains__: ClassVar[function] = ...
    __eq__: ClassVar[function] = ...
    __getitem__: ClassVar[function] = ...
    __hash__: ClassVar[None] = ...
    __reversed__: ClassVar[None] = ...
    __slots__: ClassVar[tuple] = ...

class MemoryMappedFile(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _open(self, path, mode = ...) -> Any: ...
    def create(self, path, size) -> Any: ...
    def fileno(self) -> Any: ...
    def resize(self, new_size) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class MemoryPool(_Weakrefable):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    backend_name: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def bytes_allocated(self) -> Any: ...
    def max_memory(self) -> Any: ...
    def release_unused(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Message(_Weakrefable):
    body: Any
    metadata: Any
    metadata_version: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def equals(self, Messageother) -> Any: ...
    def serialize(self, alignment = ..., memory_pool = ...) -> Any: ...
    def serialize_to(self, NativeFilesink, alignment = ..., memory_pool = ...) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class MessageReader(_Weakrefable):
    def __init__(self, *args, **kwargs) -> None: ...
    def open_stream(self, source) -> Any: ...
    def read_next_message(self) -> Any: ...
    def __iter__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class MetadataVersion(enum.IntEnum):
    class _member_type_:
        denominator: Any
        imag: Any
        numerator: Any
        real: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        @overload
        def as_integer_ratio(self) -> Any: ...
        @overload
        def as_integer_ratio(self) -> Any: ...
        @overload
        def as_integer_ratio(self) -> Any: ...
        def bit_count(self) -> Any: ...
        def bit_length(self) -> Any: ...
        def conjugate(self, *args, **kwargs) -> Any: ...
        @classmethod
        def from_bytes(cls, *args, **kwargs) -> Any: ...
        def to_bytes(self, *args, **kwargs) -> Any: ...
        def __abs__(self) -> Any: ...
        def __add__(self, other) -> Any: ...
        def __and__(self, other) -> Any: ...
        def __bool__(self) -> Any: ...
        def __ceil__(self, *args, **kwargs) -> Any: ...
        def __divmod__(self, other) -> Any: ...
        def __eq__(self, other) -> Any: ...
        def __float__(self) -> Any: ...
        def __floor__(self, *args, **kwargs) -> Any: ...
        def __floordiv__(self, other) -> Any: ...
        def __format__(self, *args, **kwargs) -> Any: ...
        def __ge__(self, other) -> Any: ...
        def __getnewargs__(self, *args, **kwargs) -> Any: ...
        def __gt__(self, other) -> Any: ...
        def __hash__(self) -> Any: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> Any: ...
        def __invert__(self) -> Any: ...
        def __le__(self, other) -> Any: ...
        def __lshift__(self, other) -> Any: ...
        def __lt__(self, other) -> Any: ...
        def __mod__(self, other) -> Any: ...
        def __mul__(self, other) -> Any: ...
        def __ne__(self, other) -> Any: ...
        def __neg__(self) -> Any: ...
        def __or__(self, other) -> Any: ...
        def __pos__(self) -> Any: ...
        def __pow__(self, other) -> Any: ...
        def __radd__(self, other) -> Any: ...
        def __rand__(self, other) -> Any: ...
        def __rdivmod__(self, other) -> Any: ...
        def __rfloordiv__(self, other) -> Any: ...
        def __rlshift__(self, other) -> Any: ...
        def __rmod__(self, other) -> Any: ...
        def __rmul__(self, other) -> Any: ...
        def __ror__(self, other) -> Any: ...
        def __round__(self) -> Any: ...
        def __rpow__(self, other) -> Any: ...
        def __rrshift__(self, other) -> Any: ...
        def __rshift__(self, other) -> Any: ...
        def __rsub__(self, other) -> Any: ...
        def __rtruediv__(self, other) -> Any: ...
        def __rxor__(self, other) -> Any: ...
        def __sizeof__(self) -> Any: ...
        def __sub__(self, other) -> Any: ...
        def __truediv__(self, other) -> Any: ...
        def __trunc__(self) -> Any: ...
        def __xor__(self, other) -> Any: ...
    __new__: ClassVar[function] = ...
    V1: ClassVar[importlib._bootstrap.MetadataVersion] = ...
    V2: ClassVar[importlib._bootstrap.MetadataVersion] = ...
    V3: ClassVar[importlib._bootstrap.MetadataVersion] = ...
    V4: ClassVar[importlib._bootstrap.MetadataVersion] = ...
    V5: ClassVar[importlib._bootstrap.MetadataVersion] = ...
    _generate_next_value_: ClassVar[function] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _value2member_map_: ClassVar[dict] = ...

class MockOutputStream(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def size(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class MonthDayNano(tuple):
    n_fields: ClassVar[int] = ...
    n_sequence_fields: ClassVar[int] = ...
    n_unnamed_fields: ClassVar[int] = ...
    __match_args__: ClassVar[tuple] = ...
    days: Any
    months: Any
    nanoseconds: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class MonthDayNanoIntervalArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def to_pylist(self) -> Any: ...

class MonthDayNanoIntervalScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    value: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class NativeFile(_Weakrefable):
    _default_chunk_size: ClassVar[int] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    closed: Any
    mode: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _assert_open(self) -> Any: ...
    def _assert_readable(self) -> Any: ...
    def _assert_seekable(self) -> Any: ...
    def _assert_writable(self) -> Any: ...
    def close(self) -> Any: ...
    def download(self, stream_or_path, buffer_size = ...) -> Any: ...
    def fileno(self) -> Any: ...
    def flush(self) -> Any: ...
    def get_stream(self, file_offset, nbytes) -> Any: ...
    def isatty(self) -> Any: ...
    def metadata(self) -> Any: ...
    def read(self, nbytes = ...) -> Any: ...
    def read1(self, nbytes = ...) -> Any: ...
    def read_at(self, nbytes, offset) -> Any: ...
    def read_buffer(self, nbytes = ...) -> Any: ...
    def readable(self) -> Any: ...
    def readall(self) -> Any: ...
    def readinto(self, b) -> Any: ...
    def readline(self, size = ...) -> Any: ...
    def readlines(self, hint = ...) -> Any: ...
    def seek(self, int64_tposition, intwhence = ...) -> Any: ...
    def seekable(self) -> Any: ...
    def size(self) -> Any: ...
    def tell(self) -> Any: ...
    def truncate(self) -> Any: ...
    def upload(self, stream, buffer_size = ...) -> Any: ...
    def writable(self) -> Any: ...
    def write(self, data) -> Any: ...
    def writelines(self, lines) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, tb) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class NullArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class NullScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class NumericArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class OSFile(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def fileno(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class ProxyMemoryPool(MemoryPool):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class PyExtensionType(ExtensionType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __arrow_ext_deserialize__(cls, typecls, storage_type, serialized) -> Any: ...
    def __arrow_ext_serialize__(self) -> Any: ...
    def __reduce__(self) -> Any: ...

class PythonFile(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def readline(self, size = ...) -> Any: ...
    def readlines(self, hint = ...) -> Any: ...
    def truncate(self, pos = ...) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Queue:
    __init__: ClassVar[function] = ...
    _get: ClassVar[function] = ...
    _init: ClassVar[function] = ...
    _put: ClassVar[function] = ...
    _qsize: ClassVar[function] = ...
    empty: ClassVar[function] = ...
    full: ClassVar[function] = ...
    get: ClassVar[function] = ...
    get_nowait: ClassVar[function] = ...
    join: ClassVar[function] = ...
    put: ClassVar[function] = ...
    put_nowait: ClassVar[function] = ...
    qsize: ClassVar[function] = ...
    task_done: ClassVar[function] = ...
    @classmethod
    def __class_getitem__(cls, *args, **kwargs) -> Any: ...

class QueueEmpty(Exception): ...

class ReadStats(importlib._bootstrap.ReadStats):
    __slots__: ClassVar[tuple] = ...

class RecordBatch(_PandasConvertible):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    columns: Any
    nbytes: Any
    num_columns: Any
    num_rows: Any
    schema: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _column(self, inti) -> Any: ...
    def _ensure_integer_index(self, i) -> Any: ...
    def _export_to_c(self, out_ptr, out_schema_ptr = ...) -> Any: ...
    def _import_from_c(self, in_ptr, schema) -> Any: ...
    def _to_pandas(self, options, **kwargs) -> Any: ...
    def column(self, i) -> Any: ...
    @overload
    def drop_null(self) -> Any: ...
    @overload
    def drop_null(self) -> Any: ...
    @overload
    def equals(self, other, boolcheck_metadata = ...) -> Any: ...
    @overload
    def equals(self, batch) -> Any: ...
    @overload
    def equals(self, batch_0) -> Any: ...
    @overload
    def equals(self, batch_1) -> Any: ...
    @overload
    def equals(self, batch_1, check_metadata = ...) -> Any: ...
    def field(self, i) -> Any: ...
    @overload
    def filter(self, mask, null_selection_behavior = ...) -> Any: ...
    @overload
    def filter(self, mask) -> Any: ...
    @overload
    def filter(self, mask, null_selection_behavior = ...) -> Any: ...
    def from_arrays(self, listarrays, names = ..., schema = ..., metadata = ...) -> Any: ...
    @overload
    @classmethod
    def from_pandas(cls, typecls, df, Schemaschema = ..., preserve_index = ..., nthreads = ..., columns = ...) -> Any: ...
    @overload
    @classmethod
    def from_pandas(cls, df) -> Any: ...
    @overload
    @classmethod
    def from_pandas(cls, df, schema = ...) -> Any: ...
    @overload
    @classmethod
    def from_pandas(cls, df, columns = ...) -> Any: ...
    @overload
    def from_pydict(self, mapping, schema = ..., metadata = ...) -> Any: ...
    @overload
    def from_pydict(self, pydict) -> Any: ...
    @overload
    def from_pydict(self, pydict) -> Any: ...
    @overload
    def from_pydict(self, pydict, schema = ...) -> Any: ...
    @overload
    def from_pylist(self, mapping, schema = ..., metadata = ...) -> Any: ...
    @overload
    def from_pylist(self, pylist) -> Any: ...
    @overload
    def from_pylist(self, pylist) -> Any: ...
    @overload
    def from_pylist(self, pylist, metadata = ...) -> Any: ...
    @overload
    def from_struct_array(self, StructArraystruct_array) -> Any: ...
    @overload
    def from_struct_array(self, struct) -> Any: ...
    @overload
    def get_total_buffer_size(self) -> Any: ...
    @overload
    def get_total_buffer_size(self) -> Any: ...
    def replace_schema_metadata(self, metadata = ...) -> Any: ...
    @overload
    def serialize(self, memory_pool = ...) -> Any: ...
    @overload
    def serialize(self) -> Any: ...
    @overload
    def slice(self, offset = ..., length = ...) -> Any: ...
    @overload
    def slice(self, offset = ...) -> Any: ...
    @overload
    def slice(self, length = ...) -> Any: ...
    @overload
    def slice(self, offset = ..., length = ...) -> Any: ...
    def take(self, indices) -> Any: ...
    @overload
    def to_pydict(self) -> Any: ...
    @overload
    def to_pydict(self) -> Any: ...
    @overload
    def to_pylist(self) -> Any: ...
    @overload
    def to_pylist(self) -> Any: ...
    def to_string(self, show_metadata = ...) -> Any: ...
    def validate(self, *args, **kwargs) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __sizeof__(self) -> Any: ...

class RecordBatchReader(_Weakrefable):
    schema: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _export_to_c(self, out_ptr) -> Any: ...
    def _import_from_c(self, in_ptr) -> Any: ...
    def close(self) -> Any: ...
    def from_batches(self, schema, batches) -> Any: ...
    def read_all(self) -> Any: ...
    def read_next_batch(self) -> Any: ...
    def read_pandas(self, **options) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> Any: ...
    def __iter__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class ResizableBuffer(Buffer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def resize(self, int64_tnew_size, shrink_to_fit = ...) -> Any: ...

class RuntimeInfo(tuple):
    _asdict: ClassVar[function] = ...
    _field_defaults: ClassVar[dict] = ...
    _fields: ClassVar[tuple] = ...
    _replace: ClassVar[function] = ...
    __getnewargs__: ClassVar[function] = ...
    __match_args__: ClassVar[tuple] = ...
    __slots__: ClassVar[tuple] = ...
    detected_simd_level: Any
    simd_level: Any
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def _make(cls, *args, **kwargs) -> Any: ...

class Scalar(_Weakrefable):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    is_valid: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...
    def cast(self, target_type) -> Any: ...
    def equals(self, Scalarother) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __hash__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...

class Schema(_Weakrefable):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    metadata: Any
    names: Any
    pandas_metadata: Any
    types: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _export_to_c(self, out_ptr) -> Any: ...
    def _field(self, inti) -> Any: ...
    def _import_from_c(self, in_ptr) -> Any: ...
    def add_metadata(self, metadata) -> Any: ...
    @overload
    def append(self, Fieldfield) -> Any: ...
    @overload
    def append(self) -> Any: ...
    @overload
    def empty_table(self) -> Any: ...
    @overload
    def empty_table(self) -> Any: ...
    @overload
    def equals(self, Schemaother, boolcheck_metadata = ...) -> Any: ...
    @overload
    def equals(self, schema1) -> Any: ...
    @overload
    def equals(self, schema2) -> Any: ...
    def field(self, i) -> Any: ...
    def field_by_name(self, name) -> Any: ...
    @overload
    @classmethod
    def from_pandas(cls, typecls, df, preserve_index = ...) -> Any: ...
    @overload
    @classmethod
    def from_pandas(cls, df) -> Any: ...
    def get_all_field_indices(self, name) -> Any: ...
    def get_field_index(self, name) -> Any: ...
    def insert(self, inti, Fieldfield) -> Any: ...
    def remove(self, inti) -> Any: ...
    @overload
    def remove_metadata(self) -> Any: ...
    @overload
    def remove_metadata(self) -> Any: ...
    @overload
    def serialize(self, memory_pool = ...) -> Any: ...
    @overload
    def serialize(self) -> Any: ...
    def set(self, inti, Fieldfield) -> Any: ...
    def to_string(self, truncate_metadata = ..., show_field_metadata = ..., show_schema_metadata = ...) -> Any: ...
    def with_metadata(self, metadata) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __hash__(self) -> Any: ...
    def __iter__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __sizeof__(self) -> Any: ...

class SerializationCallbackError(ArrowSerializationError):
    def __init__(self, message, example_object) -> Any: ...

class SerializationContext(_Weakrefable):
    def __init__(self, *args, **kwargs) -> None: ...
    def _deserialize_callback(self, serialized_obj) -> Any: ...
    def _serialize_callback(self, obj) -> Any: ...
    def clone(self) -> Any: ...
    def deserialize(self, what) -> Any: ...
    def deserialize_components(self, what) -> Any: ...
    def register_type(self, type_, type_id, pickle = ..., custom_serializer = ..., custom_deserializer = ...) -> Any: ...
    def serialize(self, obj) -> Any: ...
    def serialize_to(self, value, sink) -> Any: ...
    def set_pickle(self, serializer, deserializer) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SerializedPyObject(_Weakrefable):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    base: Any
    total_bytes: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def deserialize(self, SerializationContextcontext = ...) -> Any: ...
    def from_components(self, components) -> Any: ...
    def to_buffer(self, nthreads = ...) -> Any: ...
    def to_components(self, memory_pool = ...) -> Any: ...
    def write_to(self, sink) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SignalStopHandler:
    stop_token: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _init_signals(self) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, exc_tb) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseCOOTensor(_Weakrefable):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    dim_names: Any
    has_canonical_format: Any
    is_mutable: Any
    ndim: Any
    non_zero_length: Any
    shape: Any
    size: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def dim_name(self, i) -> Any: ...
    def equals(self, SparseCOOTensorother) -> Any: ...
    @classmethod
    def from_dense_numpy(cls, typecls, obj, dim_names = ...) -> Any: ...
    def from_numpy(self, data, coords, shape, dim_names = ...) -> Any: ...
    def from_pydata_sparse(self, obj, dim_names = ...) -> Any: ...
    def from_scipy(self, obj, dim_names = ...) -> Any: ...
    def from_tensor(self, obj) -> Any: ...
    def to_numpy(self) -> Any: ...
    def to_pydata_sparse(self) -> Any: ...
    def to_scipy(self) -> Any: ...
    def to_tensor(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseCSCMatrix(_Weakrefable):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    dim_names: Any
    is_mutable: Any
    ndim: Any
    non_zero_length: Any
    shape: Any
    size: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def dim_name(self, i) -> Any: ...
    def equals(self, SparseCSCMatrixother) -> Any: ...
    @classmethod
    def from_dense_numpy(cls, typecls, obj, dim_names = ...) -> Any: ...
    def from_numpy(self, data, indptr, indices, shape, dim_names = ...) -> Any: ...
    def from_scipy(self, obj, dim_names = ...) -> Any: ...
    def from_tensor(self, obj) -> Any: ...
    def to_numpy(self) -> Any: ...
    def to_scipy(self) -> Any: ...
    def to_tensor(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseCSFTensor(_Weakrefable):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    dim_names: Any
    is_mutable: Any
    ndim: Any
    non_zero_length: Any
    shape: Any
    size: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def dim_name(self, i) -> Any: ...
    def equals(self, SparseCSFTensorother) -> Any: ...
    @classmethod
    def from_dense_numpy(cls, typecls, obj, dim_names = ...) -> Any: ...
    def from_numpy(self, data, indptr, indices, shape, axis_order = ..., dim_names = ...) -> Any: ...
    def from_tensor(self, obj) -> Any: ...
    def to_numpy(self) -> Any: ...
    def to_tensor(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseCSRMatrix(_Weakrefable):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    dim_names: Any
    is_mutable: Any
    ndim: Any
    non_zero_length: Any
    shape: Any
    size: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def dim_name(self, i) -> Any: ...
    def equals(self, SparseCSRMatrixother) -> Any: ...
    @classmethod
    def from_dense_numpy(cls, typecls, obj, dim_names = ...) -> Any: ...
    def from_numpy(self, data, indptr, indices, shape, dim_names = ...) -> Any: ...
    def from_scipy(self, obj, dim_names = ...) -> Any: ...
    def from_tensor(self, obj) -> Any: ...
    def to_numpy(self) -> Any: ...
    def to_scipy(self) -> Any: ...
    def to_tensor(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseUnionType(UnionType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class StopToken:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class StringArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def from_buffers(self, intlength, Buffervalue_offsets, Bufferdata, Buffernull_bitmap = ..., intnull_count = ..., intoffset = ...) -> Any: ...

class StringBuilder(_Weakrefable):
    null_count: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def append(self, value) -> Any: ...
    def append_values(self, values) -> Any: ...
    def finish(self) -> Any: ...
    def __len__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class StringScalar(BinaryScalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class StructArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def field(self, index) -> Any: ...
    def flatten(self, MemoryPoolmemory_pool = ...) -> Any: ...
    def from_arrays(self, arrays, names = ..., fields = ..., mask = ..., memory_pool = ...) -> Any: ...

class StructScalar(Scalar, collections.abc.Mapping):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _as_py_tuple(self) -> Any: ...
    def as_py(self) -> Any: ...
    def items(self) -> Any: ...
    def __contains__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> Any: ...

class StructType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def field(self, i) -> Field: ...
    def get_all_field_indices(self, name) -> Any: ...
    def get_field_index(self, name) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> Any: ...
    def __reduce__(self) -> Any: ...

class Table(_PandasConvertible):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    column_names: Any
    columns: Any
    nbytes: Any
    num_columns: Any
    num_rows: Any
    schema: Any
    shape: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _column(self, inti) -> Any: ...
    def _ensure_integer_index(self, i) -> Any: ...
    def _to_pandas(self, options, categories = ..., ignore_metadata = ..., types_mapper = ...) -> Any: ...
    def add_column(self, inti, field_, column) -> Any: ...
    def append_column(self, field_, column) -> Any: ...
    def cast(self, Schematarget_schema, safe = ..., options = ...) -> Any: ...
    def column(self, i) -> Any: ...
    @overload
    def combine_chunks(self, MemoryPoolmemory_pool = ...) -> Any: ...
    @overload
    def combine_chunks(self) -> Any: ...
    def drop(self, columns) -> Any: ...
    @overload
    def drop_null(self) -> Any: ...
    @overload
    def drop_null(self) -> Any: ...
    @overload
    def equals(self, Tableother, boolcheck_metadata = ...) -> Any: ...
    @overload
    def equals(self, table) -> Any: ...
    @overload
    def equals(self, table_0) -> Any: ...
    @overload
    def equals(self, table_1) -> Any: ...
    @overload
    def equals(self, table_1, check_metadata = ...) -> Any: ...
    def field(self, i) -> Any: ...
    @overload
    def filter(self, mask, null_selection_behavior = ...) -> Any: ...
    @overload
    def filter(self, expr) -> Any: ...
    @overload
    def filter(self, mask) -> Any: ...
    @overload
    def filter(self, mask, null_selection_behavior = ...) -> Any: ...
    @overload
    def flatten(self, MemoryPoolmemory_pool = ...) -> Any: ...
    @overload
    def flatten(self) -> Any: ...
    def from_arrays(self, arrays, names = ..., schema = ..., metadata = ...) -> Any: ...
    def from_batches(self, batches, Schemaschema = ...) -> Any: ...
    @overload
    @classmethod
    def from_pandas(cls, typecls, df, Schemaschema = ..., preserve_index = ..., nthreads = ..., columns = ..., boolsafe = ...) -> Any: ...
    @overload
    @classmethod
    def from_pandas(cls, df) -> Any: ...
    @overload
    def from_pydict(self, mapping, schema = ..., metadata = ...) -> Any: ...
    @overload
    def from_pydict(self, pydict) -> Any: ...
    @overload
    def from_pydict(self, pydict) -> Any: ...
    @overload
    def from_pydict(self, pydict, metadata = ...) -> Any: ...
    @overload
    def from_pylist(self, mapping, schema = ..., metadata = ...) -> Any: ...
    @overload
    def from_pylist(self, pylist) -> Any: ...
    @overload
    def from_pylist(self, pylist, schema = ...) -> Any: ...
    @overload
    def get_total_buffer_size(self) -> Any: ...
    @overload
    def get_total_buffer_size(self) -> Any: ...
    def group_by(self, keys) -> Any: ...
    @overload
    def itercolumns(self) -> Any: ...
    @overload
    def itercolumns(self) -> Any: ...
    def join(self, right_table, keys, right_keys = ..., join_type = ..., left_suffix = ..., right_suffix = ..., coalesce_keys = ..., use_threads = ...) -> Any: ...
    def remove_column(self, inti) -> Any: ...
    @overload
    def rename_columns(self, names) -> Any: ...
    @overload
    def rename_columns(self, new_names) -> Any: ...
    @overload
    def replace_schema_metadata(self, metadata = ...) -> Any: ...
    @overload
    def replace_schema_metadata(self) -> Any: ...
    @overload
    def replace_schema_metadata(self, metadata = ...) -> Any: ...
    def select(self, columns) -> Any: ...
    def set_column(self, inti, field_, column) -> Any: ...
    @overload
    def slice(self, offset = ..., length = ...) -> Any: ...
    @overload
    def slice(self, length = ...) -> Any: ...
    @overload
    def slice(self, offset = ...) -> Any: ...
    @overload
    def slice(self, offset = ..., length = ...) -> Any: ...
    def sort_by(self, sorting) -> Any: ...
    def take(self, indices) -> Any: ...
    @overload
    def to_batches(self, max_chunksize = ...) -> Any: ...
    @overload
    def to_batches(self) -> Any: ...
    @overload
    def to_batches(self, max_chunksize = ...) -> Any: ...
    @overload
    def to_batches(self, max_chunksize = ...) -> Any: ...
    @overload
    def to_pydict(self) -> Any: ...
    @overload
    def to_pydict(self) -> Any: ...
    @overload
    def to_pylist(self) -> Any: ...
    @overload
    def to_pylist(self) -> Any: ...
    @overload
    def to_reader(self, max_chunksize = ...) -> Any: ...
    @overload
    def to_reader(self) -> Any: ...
    @overload
    def to_reader(self) -> Any: ...
    def to_string(self, *args, **kwargs) -> Any: ...
    @overload
    def unify_dictionaries(self, MemoryPoolmemory_pool = ...) -> Any: ...
    @overload
    def unify_dictionaries(self) -> Any: ...
    def validate(self, *args, **kwargs) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __sizeof__(self) -> Any: ...

class TableGroupBy:
    def __init__(self, table, keys) -> Any: ...
    def aggregate(self, aggregations) -> Any: ...

class Tensor(_Weakrefable):
    __hash__: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    dim_names: Any
    is_contiguous: Any
    is_mutable: Any
    ndim: Any
    shape: Any
    size: Any
    strides: Any
    type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def dim_name(self, i) -> Any: ...
    @overload
    def equals(self, Tensorother) -> Any: ...
    @overload
    def equals(self, tensor) -> Any: ...
    @overload
    def equals(self, tensor2) -> Any: ...
    @overload
    def from_numpy(self, obj, dim_names = ...) -> Any: ...
    @overload
    def from_numpy(self, x, dim_names = ...) -> Any: ...
    @overload
    def to_numpy(self) -> Any: ...
    @overload
    def to_numpy(self) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class TextIOBase(_io._TextIOBase, io.IOBase):
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __abstractmethods__: ClassVar[frozenset] = ...

class Time32Array(NumericArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Time32Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Time32Type(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    unit: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Time64Array(NumericArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Time64Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class Time64Type(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    unit: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class TimestampArray(NumericArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class TimestampScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    value: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class TimestampType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    tz: Any
    unit: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def to_pandas_dtype(self) -> Any: ...
    def __reduce__(self) -> Any: ...

class Transcoder:
    def __init__(self, decoder, encoder) -> Any: ...
    def __call__(self, buf) -> Any: ...

class TransformInputStream(NativeFile):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class UInt16Array(IntegerArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class UInt16Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class UInt32Array(IntegerArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class UInt32Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class UInt64Array(IntegerArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class UInt64Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class UInt8Array(IntegerArray):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class UInt8Scalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class UnionArray(Array):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    offsets: Any
    type_codes: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def child(self, intpos) -> Any: ...
    @overload
    def field(self, intpos) -> Any: ...
    @overload
    def field(self, notitstypecode) -> Any: ...
    def from_dense(self, Arraytypes, Arrayvalue_offsets, listchildren, listfield_names = ..., listtype_codes = ...) -> Any: ...
    def from_sparse(self, Arraytypes, listchildren, listfield_names = ..., listtype_codes = ...) -> Any: ...

class UnionScalar(Scalar):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    type_code: Any
    value: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def as_py(self) -> Any: ...

class UnionType(DataType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    mode: Any
    type_codes: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def field(self, i) -> Field: ...
    def __getitem__(self, index) -> Any: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> Any: ...
    def __reduce__(self) -> Any: ...

class UnknownExtensionType(PyExtensionType):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __arrow_ext_serialize__(self) -> Any: ...

class UnsupportedOperation(OSError, ValueError): ...

class VersionInfo(tuple):
    _asdict: ClassVar[function] = ...
    _field_defaults: ClassVar[dict] = ...
    _fields: ClassVar[tuple] = ...
    _replace: ClassVar[function] = ...
    __getnewargs__: ClassVar[function] = ...
    __match_args__: ClassVar[tuple] = ...
    __slots__: ClassVar[tuple] = ...
    major: Any
    minor: Any
    patch: Any
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def _make(cls, *args, **kwargs) -> Any: ...

class WriteStats(importlib._bootstrap.WriteStats):
    __slots__: ClassVar[tuple] = ...

class _CRecordBatchWriter(_Weakrefable):
    stats: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def close(self) -> Any: ...
    def write(self, table_or_batch) -> Any: ...
    def write_batch(self, RecordBatchbatch) -> Any: ...
    def write_table(self, Tabletable, max_chunksize = ...) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class _ExtensionRegistryNanny(_Weakrefable):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def release_registry(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class _Metadata(_Weakrefable):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class _PandasAPIShim:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    _array_like_types: Any
    _categorical_type: Any
    _compat_module: Any
    _data_frame: Any
    _datetimetz_type: Any
    _extension_array: Any
    _extension_dtype: Any
    _index: Any
    _is_extension_array_dtype: Any
    _loose_version: Any
    _pd: Any
    _pd024: Any
    _series: Any
    _types_api: Any
    _version: Any
    categorical_type: Any
    compat: Any
    datetimetz_type: Any
    extension_dtype: Any
    has_sparse: Any
    have_pandas: Any
    loose_version: Any
    pd: Any
    version: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def assert_frame_equal(self, *args, **kwargs) -> Any: ...
    def data_frame(self, *args, **kwargs) -> Any: ...
    def get_rangeindex_attribute(self, level, name) -> Any: ...
    def get_values(self, obj) -> Any: ...
    def infer_dtype(self, obj) -> Any: ...
    def is_array_like(self, obj) -> Any: ...
    def is_categorical(self, obj) -> Any: ...
    def is_data_frame(self, obj) -> Any: ...
    def is_datetimetz(self, obj) -> Any: ...
    def is_extension_array_dtype(self, obj) -> Any: ...
    def is_index(self, obj) -> Any: ...
    def is_series(self, obj) -> Any: ...
    def is_sparse(self, obj) -> Any: ...
    def pandas_dtype(self, dtype) -> Any: ...
    def series(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class _PandasConvertible(_Weakrefable):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @overload
    def to_pandas(self, memory_pool = ..., categories = ..., boolstrings_to_categorical = ..., boolzero_copy_only = ..., boolinteger_object_nulls = ..., booldate_as_object = ..., booltimestamp_as_object = ..., booluse_threads = ..., booldeduplicate_objects = ..., boolignore_metadata = ..., boolsafe = ..., boolsplit_blocks = ..., boolself_destruct = ..., types_mapper = ...) -> Any: ...
    @overload
    def to_pandas(self) -> Any: ...
    @overload
    def to_pandas(self) -> Any: ...
    @overload
    def to_pandas(self) -> Any: ...
    @overload
    def to_pandas(self) -> Any: ...
    @overload
    def to_pandas(self) -> Any: ...
    @overload
    def to_pandas(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class _ReadPandasMixin:
    def read_pandas(self, **options) -> Any: ...

class _ReadStats(tuple):
    _asdict: ClassVar[function] = ...
    _field_defaults: ClassVar[dict] = ...
    _fields: ClassVar[tuple] = ...
    _replace: ClassVar[function] = ...
    __getnewargs__: ClassVar[function] = ...
    __match_args__: ClassVar[tuple] = ...
    __slots__: ClassVar[tuple] = ...
    num_dictionary_batches: Any
    num_dictionary_deltas: Any
    num_messages: Any
    num_record_batches: Any
    num_replaced_dictionaries: Any
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def _make(cls, *args, **kwargs) -> Any: ...

class _RecordBatchFileReader(_Weakrefable):
    num_record_batches: Any
    schema: Any
    stats: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _open(self, source, footer_offset = ..., IpcReadOptionsoptions = ..., MemoryPoolmemory_pool = ...) -> Any: ...
    def get_batch(self, inti) -> Any: ...
    def get_record_batch(self, *args, **kwargs) -> Any: ...
    def read_all(self) -> Any: ...
    def read_pandas(self, **options) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, traceback) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class _RecordBatchFileWriter(_RecordBatchStreamWriter):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _open(self, sink, Schemaschema, IpcWriteOptionsoptions = ...) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class _RecordBatchStreamReader(RecordBatchReader):
    stats: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _open(self, source, IpcReadOptionsoptions = ..., MemoryPoolmemory_pool = ...) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class _RecordBatchStreamWriter(_CRecordBatchWriter):
    _metadata_version: Any
    _use_legacy_format: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _open(self, sink, Schemaschema, IpcWriteOptionsoptions = ...) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class _Weakrefable:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class _WriteStats(tuple):
    _asdict: ClassVar[function] = ...
    _field_defaults: ClassVar[dict] = ...
    _fields: ClassVar[tuple] = ...
    _replace: ClassVar[function] = ...
    __getnewargs__: ClassVar[function] = ...
    __match_args__: ClassVar[tuple] = ...
    __slots__: ClassVar[tuple] = ...
    num_dictionary_batches: Any
    num_dictionary_deltas: Any
    num_messages: Any
    num_record_batches: Any
    num_replaced_dictionaries: Any
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def _make(cls, *args, **kwargs) -> Any: ...

class ordered_dict:
    __hash__: ClassVar[None] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def clear(self, *args, **kwargs) -> Any: ...
    def copy(self) -> ashallowcopyofD: ...
    @classmethod
    def fromkeys(cls, *args, **kwargs) -> Any: ...
    def get(self, *args, **kwargs) -> Any: ...
    def items(self, *args, **kwargs) -> Any: ...
    def keys(self, *args, **kwargs) -> Any: ...
    def pop(self, *args, **kwargs) -> Any: ...
    def popitem(self, *args, **kwargs) -> Any: ...
    def setdefault(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
    def values(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __class_getitem__(cls, *args, **kwargs) -> Any: ...
    def __contains__(self, other) -> Any: ...
    def __delitem__(self, other) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, y) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __ior__(self, other) -> Any: ...
    def __iter__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __or__(self, other) -> Any: ...
    def __reversed__(self) -> Any: ...
    def __ror__(self, other) -> Any: ...
    def __setitem__(self, index, object) -> Any: ...
    def __sizeof__(self) -> Any: ...

def __pyx_unpickle_SerializationContext(__pyx_type, long__pyx_checksum, __pyx_state) -> Any: ...
def __pyx_unpickle__PandasAPIShim(__pyx_type, long__pyx_checksum, __pyx_state) -> Any: ...
def __pyx_unpickle__PandasConvertible(__pyx_type, long__pyx_checksum, __pyx_state) -> Any: ...
def __pyx_unpickle___Pyx_EnumMeta(*args, **kwargs) -> Any: ...
def _datetime_from_int(int64_tvalue, TimeUnitunit, tzinfo = ...) -> Any: ...
def _deprecate_serialization(name) -> Any: ...
def _deserialize(obj, SerializationContextcontext = ...) -> Any: ...
def _detect_compression(path) -> Any: ...
def _empty_array(DataTypetype) -> Any: ...
def _from_pydict(cls, mapping, schema, metadata) -> Any: ...
def _from_pylist(cls, mapping, schema, metadata) -> Any: ...
def _gdb_test_session() -> Any: ...
def _get_default_context() -> Any: ...
def _handle_arrow_array_protocol(obj, type, mask, size) -> Any: ...
def _is_primitive(Typetype) -> Any: ...
def _ndarray_to_arrow_type(values, DataTypetype) -> Any: ...
def _normalize_slice(arrow_obj, slicekey) -> Any: ...
def _pc() -> Any: ...
def _read_serialized(source, base = ...) -> Any: ...
def _reconstruct_record_batch(columns, schema) -> Any: ...
def _reconstruct_table(arrays, schema) -> Any: ...
def _register_py_extension_type() -> Any: ...
def _restore_array(data) -> Any: ...
def _serialize(value, SerializationContextcontext = ...) -> Any: ...
def _unregister_py_extension_types() -> Any: ...
def allocate_buffer(int64_tsize, MemoryPoolmemory_pool = ..., resizable = ...) -> Any: ...
def array(obj, type = ..., mask = ..., size = ..., from_pandas = ..., boolsafe = ..., MemoryPoolmemory_pool = ...) -> Any: ...
def as_buffer(o) -> Any: ...
def asarray(values, type = ...) -> Any: ...
def benchmark_PandasObjectIsNull(listobj) -> Any: ...
def binary(intlength = ...) -> Any: ...
def bool_() -> Any: ...
def chunked_array(arrays, type = ...) -> Any: ...
def compress(buf, codec = ..., asbytes = ..., memory_pool = ...) -> Any: ...
def concat_arrays(arrays, MemoryPoolmemory_pool = ...) -> Any: ...
def concat_tables(tables, boolpromote = ..., MemoryPoolmemory_pool = ...) -> Any: ...
def cpu_count() -> Any: ...
def create_memory_map(path, size) -> Any: ...
def date32() -> Any: ...
def date64() -> Any: ...
def decimal128(intprecision, intscale = ...) -> DataType: ...
def decimal256(intprecision, intscale = ...) -> DataType: ...
def decompress(buf, decompressed_size = ..., codec = ..., asbytes = ..., memory_pool = ...) -> Any: ...
@overload
def default_memory_pool() -> Any: ...
@overload
def default_memory_pool() -> Any: ...
def dense_union(child_fields, type_codes = ...) -> Any: ...
def deserialize(obj, SerializationContextcontext = ...) -> Any: ...
def deserialize_components(components, SerializationContextcontext = ...) -> Any: ...
def deserialize_from(source, base, SerializationContextcontext = ...) -> Any: ...
def dictionary(index_type, value_type, boolordered = ...) -> DictionaryType: ...
def duration(unit) -> Any: ...
def enable_signal_handlers(boolenable) -> Any: ...
def encode_file_path(path) -> Any: ...
def ensure_metadata(meta, boolallow_none = ...) -> KeyValueMetadata: ...
def ensure_type(ty, boolallow_none = ...) -> DataType: ...
def field(name, type, boolnullable = ..., metadata = ...) -> Any: ...
def float16() -> Any: ...
def float32() -> Any: ...
def float64() -> Any: ...
def foreign_buffer(address, size, base = ...) -> Any: ...
def from_numpy_dtype(dtype) -> Any: ...
def frombytes(*args, **kwargs) -> Any: ...
def get_record_batch_size(RecordBatchbatch) -> Any: ...
def get_tensor_size(Tensortensor) -> Any: ...
def infer_type(values, mask = ..., from_pandas = ...) -> Any: ...
def input_stream(source, compression = ..., buffer_size = ...) -> Any: ...
def int16() -> Any: ...
def int32() -> Any: ...
def int64() -> Any: ...
def int8() -> Any: ...
def io_thread_count() -> Any: ...
def is_boolean_value(obj) -> Any: ...
def is_float_value(obj) -> Any: ...
def is_integer_value(obj) -> Any: ...
def is_named_tuple(cls) -> Any: ...
def jemalloc_memory_pool() -> Any: ...
def jemalloc_set_decay_ms(decay_ms) -> Any: ...
def large_binary() -> Any: ...
def large_list(value_type) -> LargeListType: ...
def large_string() -> Any: ...
def large_utf8() -> Any: ...
def list_(value_type, intlist_size = ...) -> Any: ...
def log_memory_allocations(enable = ...) -> Any: ...
def logging_memory_pool(MemoryPoolparent) -> Any: ...
def map_(key_type, item_type, keys_sorted = ...) -> MapType: ...
def memory_map(path, mode = ...) -> Any: ...
def mimalloc_memory_pool() -> Any: ...
def month_day_nano_interval() -> Any: ...
def null() -> Any: ...
def nulls(size, type = ..., MemoryPoolmemory_pool = ...) -> Any: ...
def output_stream(source, compression = ..., buffer_size = ...) -> Any: ...
def proxy_memory_pool(MemoryPoolparent) -> Any: ...
def py_buffer(obj) -> Any: ...
def read_message(source) -> Any: ...
def read_record_batch(obj, Schemaschema, DictionaryMemodictionary_memo = ...) -> Any: ...
def read_schema(obj, DictionaryMemodictionary_memo = ...) -> Any: ...
def read_serialized(source, base = ...) -> Any: ...
def read_tensor(source) -> Any: ...
@overload
def record_batch(data, names = ..., schema = ..., metadata = ...) -> Any: ...
@overload
def record_batch(df) -> Any: ...
@overload
def record_batch(df) -> Any: ...
@overload
def record_batch(df, my_schema) -> Any: ...
@overload
def record_batch(df, my_schema) -> Any: ...
def register_extension_type(ext_type) -> Any: ...
def repeat(value, size, MemoryPoolmemory_pool = ...) -> Any: ...
def runtime_info() -> Any: ...
def scalar(*args, **kwargs) -> Any: ...
def schema(fields, metadata = ...) -> Any: ...
def serialize(value, SerializationContextcontext = ...) -> Any: ...
def serialize_to(value, sink, SerializationContextcontext = ...) -> Any: ...
def set_cpu_count(intcount) -> Any: ...
def set_io_thread_count(intcount) -> Any: ...
def set_memory_pool(MemoryPoolpool) -> Any: ...
def sparse_union(child_fields, type_codes = ...) -> Any: ...
def string() -> Any: ...
def string_to_tzinfo(name) -> Any: ...
@overload
def struct(fields) -> Any: ...
@overload
def struct(fields) -> Any: ...
@overload
def struct(fields) -> Any: ...
def supported_memory_backends() -> Any: ...
def system_memory_pool() -> Any: ...
@overload
def table(data, names = ..., schema = ..., metadata = ..., nthreads = ...) -> Any: ...
@overload
def table(df) -> Any: ...
@overload
def table(df, my_schema) -> Any: ...
def table_to_blocks(options, Tabletable, categories, extension_columns) -> Any: ...
def time32(unit) -> Any: ...
def time64(unit) -> Any: ...
def timestamp(unit, tz = ...) -> Any: ...
def tobytes(o) -> Any: ...
def total_allocated_bytes() -> Any: ...
def transcoding_input_stream(stream, src_encoding, dest_encoding) -> Any: ...
def type_for_alias(name) -> Any: ...
def tzinfo_to_string(tz) -> Any: ...
def uint16() -> Any: ...
def uint32() -> Any: ...
def uint64() -> Any: ...
def uint8() -> Any: ...
def unify_schemas(schemas) -> Any: ...
def union(child_fields, mode, type_codes = ...) -> Any: ...
def unregister_extension_type(type_name) -> Any: ...
def utf8() -> Any: ...
def write_tensor(Tensortensor, NativeFiledest) -> Any: ...
