from pyarrow.lib import SerializationContext as SerializationContext, builtin_pickle as builtin_pickle, py_buffer as py_buffer

cloudpickle = builtin_pickle

def register_torch_serialization_handlers(serialization_context): ...
def register_default_serialization_handlers(serialization_context) -> None: ...
def default_serialization_context(): ...
